### PR TITLE
Script for local server start

### PR DESCRIPTION
**Pull request by MichaelBrueggemann**
- added a script to locally start the server
- updated the README

As we made some test commits (because we are new to using git submodules) i recommend squashing this merge commit, to keep the main git history of the upstream fork clean

### CODE REVIEW

**Comment by PondiB** [comment]
@MichaelBrueggemann, kindly change the pull request to develop branch.

**Comment by MichaelBrueggemann** [comment]
@PondiB done

**Comment by PondiB** [comment]
Squashing and merging to dev.

**Review by PondiB — COMMENTED** [review]
👍🏾

**Pull request merged**
